### PR TITLE
syntax correction

### PR DESCRIPTION
**Pull request by CB-Rambo**

### CODE REVIEW

**Comment by kvedala** [comment]
Adding "-Ofast" optimization parameter has significant performance improvements on the SSE version.
Benchmarks: [plotcycles_gcc_O3.pdf](https://github.com/BLAKE2/BLAKE2/files/1725108/plotcycles_gcc_O3.pdf) and [plotcycles_gcc_Ofast.pdf](https://github.com/BLAKE2/BLAKE2/files/1725109/plotcycles_gcc_Ofast.pdf)
Attached benchmark graphs are on a macOS with 
```
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Apple LLVM version 9.0.0 (clang-900.0.39.2)
```

**Comment by XenHat** [comment]
Please perform validity tests compared to the version without `Ofast`. I have doubts it is safe for a cryptography application.

see: https://stackoverflow.com/a/27316110/1570096
and read carefully https://gcc.gnu.org/onlinedocs/gcc-4.1.0/gcc/Optimize-Options.html

**Comment by kvedala** [comment]
Agreed, that is what I thought as well. 
I then ran the `Kat` application multiple times while comparing the outputs and have been getting consistently identical outputs. Then tested on randomly generated text file as well.

This proves only for my macOS platform with the given compiler details. For other platforms, it remains to be tested. Testing by others having access to respective platforms would be good to know; thus crowdsourcing the regression testing.

**Comment by XenHat** [comment]
I will attempt the same procedure on Windows 10 x64 soon.

**Comment by XenHat** [comment]
```bash
/cygdrive/g/source/BLAKE2/ref $  ref/genkat-json.exe > kat.ref.json && \
ofast/genkat-json.exe > kat.ofast.json && \
/usr/bin/echo "Diff for JSON files: '$(diff kat.ref.json kat.ofast.json)'"  && \
ref/genkat-c.exe > kat.c.ref.txt && \
ofast/genkat-c.exe > kat.c.ofast.txt && \
echo "Diff for TXT files: '$(diff kat.c.ref.txt kat.c.ofast.txt)'"
Diff for JSON files: ''
Diff for TXT files: ''

/cygdrive/g/source/BLAKE2/ref $ gcc -v
Using built-in specs.
COLLECT_GCC=E:\Xenhat\Downloads\~SORTME\Mingw64\MinGW\bin\gcc.exe
COLLECT_LTO_WRAPPER=e:/xenhat/downloads/~sortme/mingw64/mingw/bin/../libexec/gcc/x86_64-w64-mingw32/7.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../src/configure --enable-languages=c,c++ --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --disable-multilib --prefix=/c/temp/gcc/dest --with-sysroot=/c/temp/gcc/dest --disable-libstdcxx-pch --disable-libstdcxx-verbose --disable-nls --disable-shared --disable-win32-registry --with-tune=haswell --enable-threads=posix --enable-libgomp
Thread model: posix
gcc version 7.2.0 (GCC)
```

**Comment by kvedala** [comment]
@XenHat did you also do any benchmarks and see any improvement? You seem to be running on "Cygwin"; wouldn't you think MSYS2 would be better to generate native windows EXE?

**Comment by XenHat** [comment]
@kvedala 
```
$ file genkat-json.exe
genkat-json.exe: PE32+ executable (console) x86-64, for MS Windows
```
😉 it reports "cygwin" because I have a very strange mixed environment and cygwin's `bash` is before MSYS2 in path.

image

**Comment by XenHat** [comment]
I won't be able to test the benchmark at the moment:
```
md5.c:16:10: fatal error: openssl/md5.h: No such file or directory
 #include <openssl/md5.h>
          ^~~~~~~~~~~~~~~
```
Even though I have the openssl libs installed in the mingw package manager.

**Comment by kvedala** [comment]
I used:
```
CFLAGS += `pkg-config openssl --cflags`
LDFLAGS += `pkg-config openssl --libs`
```
and passed that on.

**Comment by XenHat** [comment]
Not having a lot of luck here, and I have to attend something else until tomorrow. 😦

**Comment by noloader** [comment]
The initial report with the fix for the missing comma seems like a good idea. The other changes don't seem related to the compile error of the missing comma.

**Comment by sneves** [comment]
Yeah, I'll take the typo fix. 

I'm skeptical that `-Ofast` is meaningfully different than `-O3` here, as it's only supposed to add `-ffast-math` and that's useful mostly for floating-point code.

**Comment by XenHat** [comment]
```bash
$ for i in {0..3}; do echo "$(time for i in {0..30}; do ./b2sum.exe ../testvectors/blake2-kat.js                               on >/dev/null; done)"; done

real    0m1.706s
user    0m0.030s
sys     0m0.765s


real    0m1.599s
user    0m0.136s
sys     0m0.688s


real    0m1.590s
user    0m0.092s
sys     0m0.672s


real    0m1.612s
user    0m0.045s
sys     0m0.687s


$ for i in {0..3}; do echo "$(time for i in {0..30}; do ./b2sum.ofast.exe ../testvectors/blake2-                               kat.json >/dev/null; done)"; done

real    0m1.697s
user    0m0.045s
sys     0m0.703s


real    0m1.573s
user    0m0.121s
sys     0m0.671s


real    0m1.614s
user    0m0.075s
sys     0m0.780s


real    0m1.588s
user    0m0.075s
sys     0m0.751s
```

**Comment by kvedala** [comment]
indeed! this test shows contradictory results. I am able to confirm that `b2sum` indeed slows down with "-Ofast". 

How would you explain the improvements observed in the "benchmark" application!

**Comment by XenHat** [comment]
> How would you explain the improvements observed in the "benchmark" application!

I would say OS and CPU cache internals, or perhaps fast math creating different branching? I'm not an expert in such low-level code

**Comment by kvedala** [comment]
considering the unknowns, I've removed the commits to the makefiles and left only one commit for the syntax correction, as the pull-request title suggested.

**Comment by noloader** [comment]
> How would you explain the improvements observed in the "benchmark" application!

Hard to say, but... one of the things you want to do *before* benchmarking is put the CPU in performance mode. If you ran the test with the CPU in *powersave* or *on-demand* mode, then the results will be slewed/inconsistent.

A script to do it is available at [`governor.sh`](https://github.com/weidai11/cryptopp/blob/master/TestScripts/governor.sh), but you need super user to run it.

**Comment by CB-Rambo** [comment]
Thank you, @noloader for the reference. Will review.

**Pull request merged**
