### PR TITLE
.NET Core Support

### PR DESCRIPTION
**Pull request by PawelGerr**
Hi,
I've added support for .NET Core (`netstandard 1.3`, .NET 4.5.1 and .NET 4.6). For that I had to switch from *.csproj to *.xproj. There is a breaking change though. The interface `IClonable` had to be removed because this interface does not exist in .NET Core but the method `Clone` is still there.
For test project I use Xunit instead of MSTest because MSTest is not ported to .NET Core (yet).
- Pawel

### CODE REVIEW

**Comment by sneves** [comment]
Hi,

There have been other people wanting to contribute C# implementations, and I will tell you the same I told them---I am not familiar with C# and thus unable to evaluate this commit properly (I did not write the `csharp` code present in this repo, and for all intents and purposes, it should now be considered unmaintained).

There is an alternative C# implementation that might be a better fit for this code: https://github.com/metadings/Blake2B.cs

**Comment by yallie** [comment]
>There is an alternative C# implementation that might be a better fit for this code: https://github.com/metadings/Blake2B.cs

The implementation you're suggesting [is somewhat incorrect](https://github.com/metadings/Blake2B.cs/issues/3).

Please consider splitting the C# version to its own repository in the same organization!
I believe that BLAKE2 organization is the first place to search for the right implementation.
Too bad that C# version is currently unmaintained :)

**Comment by zhangfelix** [comment]
Those discussion confuses me.
Is "BLAKE2/BLAKE2/csharp/" a correct implementation?

**Comment by yallie** [comment]
>Is "BLAKE2/BLAKE2/csharp/" a correct implementation?

Yes, [BLAKE2/BLAKE2/csharp](https://github.com/BLAKE2/BLAKE2/tree/master/csharp)  implementation seems to be correct.  
It gives the same results as Python's hashlib implementation of blake2 hash.
But nobody maintains it, so it doesn't support .NET Core.

[The implementation by metadings](https://github.com/metadings/Blake2B.cs) suggested as an alternative is not correct.
Also, it looks abandoned (last commit 1.5 years ago, the issues not answered, etc).

Hence, my request to split the C# implementation to its own repository and assign a maintainer.

**Comment by justdmitry** [comment]
Oh, made PR #74  before found this...
Now is 2021, we have .NET 5.0, and 6.0 is coming, and **netstandard2.0** seems have no problem with `ICloneable` - the only change in code I made is replaced VS Unit testing with Xunit.

**Pull request closed without merging**
