### PR TITLE
Updated Blake2s code to match diagonal shuffle tweak done in blake2-a…

### PR DESCRIPTION
**Pull request by sean-sn**
Updated Blake2s diagonal for dependency tweak already done elsewhere for Blake2b.  On Skylake using ICC -march=native c/b dropped from 5.22 to 4.88.

### CODE REVIEW

**Comment by sneves** [comment]
To what degree is this tested? I noticed that some of the permutations are not simple index changes. E.g., `LOAD_MSG_0_3` went from 1 to 3 instructions.

**Comment by sean-sn** [comment]
The built in library self tests passed for sse41 and sse2.  I used the emulation built in for xop.  

The first messages of the even round are no longer straightforward, hence more instructions.  Specifically LOAD_MSG_0_3 was loading 14, 12, 10, 8 which fit nicely in shuffle_ps taking the lower two dwords from one reg and the upper from another.  Now with it being 12, 10, 8, 14 that instruction no longer applies.  Perhaps the sequences could be optimized further, functionality was my primary purpose.  Hence you will see the majority of message loads only modified the final shuffle which was already in place. Without looking at execution port contention it was hard to gauge the impact of additional instructions.  My take is it appears 4.375 c/b without the use of a vector rotate instruction (only in AVX-512) is the theoretical max assuming all non critical path instructions fit underneath.  At 4.88 it felt pretty good for a general purpose flow.

**Comment by sneves** [comment]
Well, in the case of `LOAD_MSG_0_3` specifically, you don't need the `_mm_blend_epi16`; keep the original `_mm_shuffle_ps`, and rotate the result with another `_mm_shuffle_epi32`, say.

But ultimately, the instruction selection here won't matter much in the newer chips, I guess.

**Comment by sean-sn** [comment]
For msg 0 I also cheated a little and you will see I used t1 for LOAD_MSG_0_4 as well.  Probably not the best coding practice and the only place I do that.  The rationale was I only have three shuffles across the two loads instead of four.  Since shuffles are only on one port I was playing around with blend versions to see if there was an advantage.  I didn't find any but left it as is.  This goes back to the point I didn't spend much time analyzing optimal loads since it wasn't clear the benefit.

**Comment by sneves** [comment]
Oh yeah, didn't even notice the use of `t1` there. Not pretty, but it's not like this was very readable before...

**Comment by grafi-tt** [comment]
Using blend instruction instead of shuffle/unpack instructions is generally considered as a good practice in x86_64 SIMD programming. It is recommended in Intel's manual. If I remember correctly, Amd's Zen architecture has similar restriction too.

The problem is execution ports for shuffle/unpack instructions are limited. Those instruction move data across 64bit lanes, so probably they occupies large areas of circuits.

I didn't optimize to reduce shuffle/unpack instructions in https://github.com/sneves/blake2-avx2/pull/4 just because it is cumbersome. I think this optimization should be automated. Searching the optimal instruction sequence is too hard for any human.

**Pull request merged**
