### PR TITLE
Add BLAKE2b for POWER8

### PR DESCRIPTION
**Pull request by noloader**
This commit adds BLAKE2b for POWER8.

The self tests were OK on gcc112.fsffrance.org (Linux, ppc64le) and gcc119.fsffrance.org (AIX, ppc64be) using GCC and XLC compilers.

The POWER8 code is anywhere from 12 cpb faster to 2 cpb slower then C code, depending on the architecture, the compiler and cpu power settings. The BLAKE2b POWER8 code is about 2 to 2.5 cpb faster than MD5 based on the benchmarks I have access to.

The BLAKE2s gear is from the reference implementation. I don't plan on a BLAKE2s Altivec implementation. The Altivec implementation of BLAKE2s is slower than MD5 on all architecture and compilers I have access to. However, Altivec is still faster than C in most cases.

------

Here are the benchmark numbers for the benchmark program I have access to. All measurements taken at `-O3`:

`gcc119` (AIX, ppc64be):
* BLAKE2b, C++ - 17.59 cpb
* BLAKE2b, POWER8 - 5.55 cpb
* BLAKE2s, C++ - 7.74 cpb
* BLAKE2s, Altivec - 7.94 cpb

`gcc112` (Linux, ppc64le):
* BLAKE2b, C++ - 10.36 cpb
* BLAKE2b, POWER8 - 8.29 cpb
* BLAKE2s, C++ - 20.88 cpb
* BLAKE2s, Altivec - 16.52 cpb

The cpu power settings are OnDemand so it introduces a lot of variability in measurements. Measurements will swing upto about 6 or 8 cpb. You usually need to run the benchmarks several times, and take the next-to-lowest measurement (treat lowest as an outlier). I'd like to get into Performance mode, but we need sudo access for a script like [governor.sh](https://github.com/weidai11/cryptopp/blob/master/TestScripts/governor.sh).

### CODE REVIEW

**Comment by sneves** [comment]
You can try to do
```
git checkout power8
git reset --hard master
git cherry-pick add6578e006a252f0cd72d2f155c7c12529578d3
git push -f
```
to get the commit situation under control.

**Comment by noloader** [comment]
@sneves,

Thank you very much.

**Comment by sneves** [comment]
One thing I just thought of: will this work on anything prior to POWER8? If not, maybe it's misleading to have it in a `ppc` directory, instead of `power8` or something?

**Comment by sneves** [comment]
Alright, merged. Thanks for the code!

**Comment by noloader** [comment]
No problems. Thank you very much!

**Comment by noloader** [comment]
@sneves,

I would be interested to know how well the code performs. Would it be possible to benchmark the POWER8 code using SUPERCOP?

**Comment by noloader** [comment]
@sneves,

> One thing I just thought of: will this work on anything prior to POWER8?

The Blake2b code needs POWER8. The `vector unsigned long long` datatype (64x2 arrangement) was added to VSX (seen with POWER7) and POWER8 (VSX extensions are bart of the POWER8 base).

However, most of the operations on the `vector unsigned long long` datatype did not arrive until POWER8. So you could load into a `vector unsigned long long`, but you could not add two 64x2 vectors until POWER8. If you want to add two two 64x2 vectors in PWOER7, then you need code like [this](https://github.com/weidai11/cryptopp/blob/master/ppc_simd.h#L2007).

Regarding the name of the folder... Blake2s uses the `vector unsigned int` datatype (32x4 arrangement), and it can be implemented in Altivec, POWER5, POWER7, etc. If someone ever implements Blake2s on PowerPC, they can drop it in `ppc` folder.

**Pull request merged**
