### PR TITLE
Add missing SSE includes

### PR DESCRIPTION
**Pull request by noloader**
Add missing SSE includes

### CODE REVIEW

**Comment by sneves** [comment]
I don't quite understand this one. There are many `*-load-*.h` files, but only this one includes the headers? Why?

Either way, these are internal headers, meant to be included from a place where the necessary headers are already included.

**Comment by noloader** [comment]
Thanks @sneves,

> There are many *-load-*.h files, but only this one includes the headers? Why?

Both `sse/blake2b-load-sse2.h ` and `sse/blake2s-load-sse2.h ` use SSE. According to the [Intel Intrinsic Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_set_epi64), both `_mm_set_epi32` (BLAKE2s) and `_mm_set_epi64` (BLAKE2b) requires the header `<emmintrin.h>`.

If memory serves me... this caused a compile failure on Solaris. Another one that may have experienced trouble is CentOS 5. CentOS 5 tends to be a little delicate about SSE headers, too.

**Comment by sneves** [comment]
I remain confused. `blake2b-load-sse41.h` also uses SSE2 (and beyond) instrinsics, and there's no `#include` added. Why only those two files?

`<emmintrin.h>`, and others, are already included in `blake2{s,b}.c`, which is the only place these headers will be included from.

**Comment by noloader** [comment]
@sneves,

I believe the problem on Solaris is/was, SunCC does not define GCC defines, like `__SSE2__`, `__SSE3__` and friends. You have to manually define them for SunCC.

The SSE2 codepath was safe on Solaris (and hence the header `<emmintrin.h>`) because SSE2 is part of the amd64 base ISA.

**Pull request closed without merging**
