### PR TITLE
Add digest length argument to b2sum (plus minor improvements)

### PR DESCRIPTION
**Pull request by betafive**
The main change here is the addition of a "-l <length>" argument to b2sum to allow a shorter digest length to be selected.

Minor improvements:
* Use an 'algorithm' variable to store the selected algorithm name, making some of the code simpler.
* Add a .gitignore file.

### CODE REVIEW

**Comment by sneves** [comment]
Technically speaking, every output size of BLAKE2b etc is a separate hash function, it is not simply the truncated hash. So when printing digests the size should be added to the algorithm name when it is not the nominal one.

**Comment by betafive** [comment]
@sneves, that does make sense. I'll amend the last commit to include the output size in the algorithm name when it's set to a non-default value.

**Comment by betafive** [comment]
@sneves, I've amended the last commit. With the '--tag' option, the digest length is now printed in bits if it is non-default. I think bits makes more sense than bytes here as other digests are named in terms of output bits (eg. sha256 and sha512).

I'm also considering adding a '-L' option to specify the length in bits, so '-l 32' and '-L 256' would be equivalent. Does that sound useful?

**Comment by betafive** [comment]
@sneves I'm not sure I've done the right thing here. If I run blake2b() with a 32-byte output buffer it produces a different output to running blake2b() with a 64-byte output buffer and picking the first 32-bytes. Is this expected behaviour from BLAKE2b? If so I think these patches are going in the wrong direction.

**Comment by sneves** [comment]
@betafive Yes, that is expected. It is what I meant by "every output size of BLAKE2b etc is a separate hash function".

Sorry for the silence on this. I think having both bits and byte size as options is unnecessary. I think most everyone is used to bits, so I think the sane thing is to input bits, and fail if that number is not a multiple of 8.

**Comment by betafive** [comment]
@sneves: Ah ok, that's clearer now. Looking at the code in more detail I can see that the output length is mixed into the initialisation vector.

I'll re-work these patches to set the output buffer length properly and change the length argument to take a length in bits.

**Comment by betafive** [comment]
@sneves: I've changed the length argument to bits and passed the requested length into the blake2 functions. Hopefully this now does the right thing.

**Comment by sneves** [comment]
Looks good!

**Pull request merged**
