### PR TITLE
New Blake2.cs: Inheriting HashAlgorithm and IDisposable

### PR DESCRIPTION
**Pull request by metadings**
The old Blake2B CSharp implementation created a lot of objects.
If you have made `new Blake2B`, you also did `new Blake2BHasher : Hasher`, `new HashAlgorithmAdapter : HashAlgorithm`, most noteably `new Blake2BCore`, `new Blake2BConfig` and `new Blake2BTreeConfig`. So you made 5 to 6 objects.

In the new Blake2B.cs implementation, you just make one `new Blake2B` object,
which directly inherits `System.Security.Cryptography.HashAlgorithm`,
and is therefore also a `System.IDisposable`.

Usage

	using Blake2;
	using System;
	using System.Text;

	byte[] bytes = Encoding.UTF8.GetBytes(text);
	byte[] value;

	using (var hash = new Blake2B()) value = hash.ComputeHash(bytes);

Example

	~/Blake2.cs/bin/Debug $ mono ./Blake2.exe HelloWorldOfDonaldDuckAndMickeyM
	ff982bbcce1ff9d24ea1d9c06f0568cb4c612053c93876cac0ab91b3ce00a5e3b4708a146d41cb1e55e77a8863ce4229 8e22de0c34c85ee92dbcc9dab9092c6c

	~/Blake2.cs/bin/Debug $ mono ./Blake2.exe HHHHAAAALLLLOOOOWWWWEEEELLLLTTTT
	bbc9e82dbf9a8897a5ec2f6836c381dbe27ac0b8ecd9912afa67459ef9474d70a52bf24ad5dcf29dbb8004d19a387b6516cc47ffae99d59d52efc013456c6b48

### CODE REVIEW

**Comment by metadings** [comment]
Look: I even need to get rid of
- Blake2BTreeConfig and also 
- FullyUnrolled, Inline and Simple
to implement the Blake2B Compress method.

Please... wait :-)

**Comment by metadings** [comment]
Hello 😀

Are you alive?

**Comment by sneves** [comment]
Hi, I'm alive. However I know nothing of C#, having not done the C# implementation here in this repo, so I don't feel capable of judging this patch.

**Comment by metadings** [comment]
### `😊`

Would you like to take me up into your `BLAKE2 - fast secure hashing member` group?

You could add [metadings/Blake2B.cs](http://github.com/metadings/Blake2B.cs) project to the list of repositories, this is also CC0 Public Domain.

**Pull request closed without merging**
